version: '3.8'

services:
  # Servicio para PostgreSQL
  postgres:
    image: postgres:13 
    container_name: postgres-container
    environment:
      POSTGRES_DB: bd_catalogo 
      POSTGRES_USER: postgres   
      POSTGRES_PASSWORD: 123456 
    ports:
      - "5433:5432"  
    volumes:
      - postgres_data:/var/lib/postgresql/data  
    networks:
      - app-network

  # Servicio para la API REST
  api:
    build:
      context: .  # Ruta al Dockerfile de tu API
    container_name: api-rest-container
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=bd_catalogo;Username=postgres;Password=123456
    ports:
      - "5000:80"  
    depends_on:
      - postgres  
    networks:
      - app-network

# Volumen para persistencia de datos de PostgreSQL
volumes:
  postgres_data:

# Red de la aplicación para que los servicios
networks:
  app-network:
    driver: bridge
